config/routes.rb
PhotoBlog::Application.routes.draw do
  root :to => "phlogs#index"
  resources :phlogs

end

app/models/phlog.rb
class Phlog < ActiveRecord::Base
  attr_accessible :name, :image
  mount_uploader :image, ImageUploader

  after_save :enqueue_image

  def image_name
    File.basename(image.path || image.filename) if image
  end

  def enqueue_image
    ImageWorker.perform_async(id, key) if key.present?
  end

  class ImageWorker
    include Sidekiq::Worker

    def perform(id, key)
      phlog = Phlog.find(id)
      phlog.key = key
      phlog.remote_image_url = phlog.image.direct_fog_url(with_path: true)
      phlog.save!
      phlog.update_column(:image_processed, true)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/phlogs_controller.rb
class PhlogsController < ApplicationController
  # GET /phlogs
  # GET /phlogs.json
  def index
    @phlogs = Phlog.all
    @uploader = Phlog.new.image
    @uploader.success_action_redirect = new_phlog_url
  end

  # GET /phlogs/1
  # GET /phlogs/1.json
  def show
    @phlog = Phlog.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @phlog }
    end
  end

  # GET /phlogs/new
  # GET /phlogs/new.json
  def new
    @phlog = Phlog.new(key: params[:key])
  end

  # GET /phlogs/1/edit
  def edit
    @phlog = Phlog.find(params[:id])
  end

  # POST /phlogs
  # POST /phlogs.json
  def create
    @phlog = Phlog.new(params[:phlog])
    if @phlog.save
      redirect_to phlogs_url, notice: "Phlog was successfully created."
    else
      render :action => 'new'
    end
  end

  # PUT /phlogs/1
  # PUT /phlogs/1.json
  def update
    @phlog = Phlog.find(params[:id])

    respond_to do |format|
      if @phlog.update_attributes(params[:phlog])
        format.html { redirect_to @phlog, notice: 'Phlog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @phlog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phlogs/1
  # DELETE /phlogs/1.json
  def destroy
    @phlog = Phlog.find(params[:id])
    @phlog.destroy

    respond_to do |format|
      format.html { redirect_to phlogs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/phlogs_helper.rb
module PhlogsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PhotoBlog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/phlogs/_form.html.erb
<%= form_for @phlog, :html => {:multipart => true} do |f| %>
  <% if @phlog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@phlog.errors.count, "error") %> prohibited this phlog from being saved:</h2>

      <ul>
      <% @phlog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :key %>

  <p>File: <%= @phlog.image_name %></p>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/phlogs/_phlog.html.erb
<div class="phlog">
  <% if phlog.image_processed? %>
    <%= link_to image_tag(phlog.image_url(:thumb)), phlog if phlog.image? %>
  <% else %>
    <em>Processing...</em>
  <% end %>
  <div class="name"><%= phlog.name %></div>
  <div class="actions">
    <%= link_to "edit", edit_phlog_path(phlog) %> |
    <%= link_to "remove", phlog, :confirm => 'Are you sure?', :method => :delete %>
  </div>
</div>

app/views/phlogs/edit.html.erb
<h1>Editing phlog</h1>

<%= render 'form' %>

<%= link_to 'Show', @phlog %> |
<%= link_to 'Back', phlogs_path %>

app/views/phlogs/index.html.erb
<h1>List of Phlogs</h1>

<div id="phlogs">
  <%= render @phlogs %>
</div>
<div class="clear"></div>

<%= direct_upload_form_for @uploader do |f| %>
  <p><%= f.file_field :image %></p>
  <p><%= f.submit "Upload Image" %></p>
<% end %>

app/views/phlogs/new.html.erb
<h1>New phlog</h1>

<%= render 'form' %>

<%= link_to 'Back', phlogs_path %>

app/views/phlogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @phlog.name %>
</p>
<div class="phlog">
  <%= image_tag @phlog.image_url(:thumb).to_s %>
</div>

<%= link_to 'Edit', edit_phlog_path(@phlog) %> |
<%= link_to 'Destroy', phlog, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back to Phlogs', phlogs_path %>